name: Build windows release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: setup node
      uses: actions/setup-node@v4
      with:
          node-version: '22.3.0'

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: tauri-v2

    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          node-modules-

    - name: Cache Rust build artifacts
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo
          src-tauri/target
        key: rust-cache-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          rust-cache-${{ runner.os }}-

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run tauri

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tauri-build
        path: src-tauri/target/release/bundle/